name: 'Test Recipe 03'
description: "An example Drupal recipe description"
type: 'Content Type'

install:
  - node
config:
  import:
    node:
      - field.storage.node.field_color
      - field.field.node.car.field_color
      - core.entity_form_display.node.car.default
      - core.entity_view_display.node.car.teaser
      - core.entity_view_display.node.car.default
